package com.spring.pojo;

public class CommentVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_video.id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_video.comment_id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_video.video_id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    private Integer videoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_video.id
     *
     * @return the value of comment_video.id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_video.id
     *
     * @param id the value for comment_video.id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_video.comment_id
     *
     * @return the value of comment_video.comment_id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_video.comment_id
     *
     * @param commentId the value for comment_video.comment_id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_video.video_id
     *
     * @return the value of comment_video.video_id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_video.video_id
     *
     * @param videoId the value for comment_video.video_id
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
}