package com.spring.pojo;

public class CommentRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_relation.id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_relation.parent_id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_relation.child_id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    private Integer childId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_relation.id
     *
     * @return the value of comment_relation.id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_relation.id
     *
     * @param id the value for comment_relation.id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_relation.parent_id
     *
     * @return the value of comment_relation.parent_id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_relation.parent_id
     *
     * @param parentId the value for comment_relation.parent_id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_relation.child_id
     *
     * @return the value of comment_relation.child_id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public Integer getChildId() {
        return childId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_relation.child_id
     *
     * @param childId the value for comment_relation.child_id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public void setChildId(Integer childId) {
        this.childId = childId;
    }
}