package com.spring.pojo;

public class PicVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_video.id
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_video.videoid
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    private Integer videoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_video.picpath
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    private String picpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_video.id
     *
     * @return the value of pic_video.id
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_video.id
     *
     * @param id the value for pic_video.id
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_video.videoid
     *
     * @return the value of pic_video.videoid
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    public Integer getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_video.videoid
     *
     * @param videoid the value for pic_video.videoid
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    public void setVideoid(Integer videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_video.picpath
     *
     * @return the value of pic_video.picpath
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_video.picpath
     *
     * @param picpath the value for pic_video.picpath
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }
}