package com.spring.pojo;

public class UserTopic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.userid
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.topicid
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    private Integer topicid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.id
     *
     * @return the value of user_topic.id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.id
     *
     * @param id the value for user_topic.id
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.userid
     *
     * @return the value of user_topic.userid
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.userid
     *
     * @param userid the value for user_topic.userid
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.topicid
     *
     * @return the value of user_topic.topicid
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.topicid
     *
     * @param topicid the value for user_topic.topicid
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }
}