package com.my.pojo;

public class BehaviorType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_type.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_type.name
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_type.id
     *
     * @return the value of behavior_type.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_type.id
     *
     * @param id the value for behavior_type.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_type.name
     *
     * @return the value of behavior_type.name
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_type.name
     *
     * @param name the value for behavior_type.name
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}