package com.my.pojo;

public class BehaviorContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_content.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_content.content
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_content.id
     *
     * @return the value of behavior_content.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_content.id
     *
     * @param id the value for behavior_content.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_content.content
     *
     * @return the value of behavior_content.content
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_content.content
     *
     * @param content the value for behavior_content.content
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}