package com.my.pojo;

public class BehaviorWeight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_weight.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_weight.weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_weight.description
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_weight.id
     *
     * @return the value of behavior_weight.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_weight.id
     *
     * @param id the value for behavior_weight.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_weight.weight
     *
     * @return the value of behavior_weight.weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_weight.weight
     *
     * @param weight the value for behavior_weight.weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_weight.description
     *
     * @return the value of behavior_weight.description
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_weight.description
     *
     * @param description the value for behavior_weight.description
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}