package com.my.pojo;

public class Classify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classify.id
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classify.classify_name
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    private String classifyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classify.id
     *
     * @return the value of classify.id
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classify.id
     *
     * @param id the value for classify.id
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classify.classify_name
     *
     * @return the value of classify.classify_name
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classify.classify_name
     *
     * @param classifyName the value for classify.classify_name
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName == null ? null : classifyName.trim();
    }
}