package com.my.pojo;

public class FollowUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_user.idfollow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    private Integer idfollowUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_user.puid
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    private Integer puid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_user.fuid
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    private Integer fuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_user.idfollow_user
     *
     * @return the value of follow_user.idfollow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    public Integer getIdfollowUser() {
        return idfollowUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_user.idfollow_user
     *
     * @param idfollowUser the value for follow_user.idfollow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    public void setIdfollowUser(Integer idfollowUser) {
        this.idfollowUser = idfollowUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_user.puid
     *
     * @return the value of follow_user.puid
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    public Integer getPuid() {
        return puid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_user.puid
     *
     * @param puid the value for follow_user.puid
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    public void setPuid(Integer puid) {
        this.puid = puid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_user.fuid
     *
     * @return the value of follow_user.fuid
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    public Integer getFuid() {
        return fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_user.fuid
     *
     * @param fuid the value for follow_user.fuid
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    public void setFuid(Integer fuid) {
        this.fuid = fuid;
    }
}