package com.my.pojo;

public class UserBehavior {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_behavior.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_behavior.uid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_behavior.btypeid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer btypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_behavior.bcontentid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer bcontentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_behavior.bcontextid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer bcontextid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_behavior.bweight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    private Integer bweight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_behavior.id
     *
     * @return the value of user_behavior.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_behavior.id
     *
     * @param id the value for user_behavior.id
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_behavior.uid
     *
     * @return the value of user_behavior.uid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_behavior.uid
     *
     * @param uid the value for user_behavior.uid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_behavior.btypeid
     *
     * @return the value of user_behavior.btypeid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getBtypeid() {
        return btypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_behavior.btypeid
     *
     * @param btypeid the value for user_behavior.btypeid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setBtypeid(Integer btypeid) {
        this.btypeid = btypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_behavior.bcontentid
     *
     * @return the value of user_behavior.bcontentid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getBcontentid() {
        return bcontentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_behavior.bcontentid
     *
     * @param bcontentid the value for user_behavior.bcontentid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setBcontentid(Integer bcontentid) {
        this.bcontentid = bcontentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_behavior.bcontextid
     *
     * @return the value of user_behavior.bcontextid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getBcontextid() {
        return bcontextid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_behavior.bcontextid
     *
     * @param bcontextid the value for user_behavior.bcontextid
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setBcontextid(Integer bcontextid) {
        this.bcontextid = bcontextid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_behavior.bweight
     *
     * @return the value of user_behavior.bweight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public Integer getBweight() {
        return bweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_behavior.bweight
     *
     * @param bweight the value for user_behavior.bweight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    public void setBweight(Integer bweight) {
        this.bweight = bweight;
    }
}