package com.my.pojo;

public class UserVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.id
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.userid
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.videoid
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    private Integer videoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.id
     *
     * @return the value of user_video.id
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.id
     *
     * @param id the value for user_video.id
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.userid
     *
     * @return the value of user_video.userid
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.userid
     *
     * @param userid the value for user_video.userid
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.videoid
     *
     * @return the value of user_video.videoid
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    public Integer getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.videoid
     *
     * @param videoid the value for user_video.videoid
     *
     * @mbggenerated Mon Oct 08 11:31:16 CST 2018
     */
    public void setVideoid(Integer videoid) {
        this.videoid = videoid;
    }
}