package com.my.pojo;

public class VideoClassify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_classify.id
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_classify.vid
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_classify.cid
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_classify.id
     *
     * @return the value of video_classify.id
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_classify.id
     *
     * @param id the value for video_classify.id
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_classify.vid
     *
     * @return the value of video_classify.vid
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_classify.vid
     *
     * @param vid the value for video_classify.vid
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_classify.cid
     *
     * @return the value of video_classify.cid
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_classify.cid
     *
     * @param cid the value for video_classify.cid
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}