package com.my.pojo;

public class VideoLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_like.id
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_like.uid
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_like.vid
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    private Integer vid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_like.id
     *
     * @return the value of video_like.id
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_like.id
     *
     * @param id the value for video_like.id
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_like.uid
     *
     * @return the value of video_like.uid
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_like.uid
     *
     * @param uid the value for video_like.uid
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_like.vid
     *
     * @return the value of video_like.vid
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_like.vid
     *
     * @param vid the value for video_like.vid
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }
}