package com.my.pojo;

public class VideoWatch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_watch.id
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_watch.vid
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_watch.watch_times
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    private Integer watchTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_watch.id
     *
     * @return the value of video_watch.id
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_watch.id
     *
     * @param id the value for video_watch.id
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_watch.vid
     *
     * @return the value of video_watch.vid
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_watch.vid
     *
     * @param vid the value for video_watch.vid
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_watch.watch_times
     *
     * @return the value of video_watch.watch_times
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    public Integer getWatchTimes() {
        return watchTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_watch.watch_times
     *
     * @param watchTimes the value for video_watch.watch_times
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    public void setWatchTimes(Integer watchTimes) {
        this.watchTimes = watchTimes;
    }
}