package com.my.dao;

import com.my.pojo.BehaviorType;
import com.my.pojo.BehaviorTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BehaviorTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int countByExample(BehaviorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int deleteByExample(BehaviorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int insert(BehaviorType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int insertSelective(BehaviorType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    List<BehaviorType> selectByExample(BehaviorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    BehaviorType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") BehaviorType record, @Param("example") BehaviorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByExample(@Param("record") BehaviorType record, @Param("example") BehaviorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(BehaviorType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_type
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByPrimaryKey(BehaviorType record);
}