package com.my.dao;

import com.my.pojo.BehaviorWeight;
import com.my.pojo.BehaviorWeightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BehaviorWeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int countByExample(BehaviorWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int deleteByExample(BehaviorWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int insert(BehaviorWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int insertSelective(BehaviorWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    List<BehaviorWeight> selectByExample(BehaviorWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    BehaviorWeight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") BehaviorWeight record, @Param("example") BehaviorWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByExample(@Param("record") BehaviorWeight record, @Param("example") BehaviorWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(BehaviorWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_weight
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByPrimaryKey(BehaviorWeight record);
}