package com.my.dao;

import com.my.pojo.BehaviorContext;
import com.my.pojo.BehaviorContextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BehaviorContextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int countByExample(BehaviorContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int deleteByExample(BehaviorContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int insert(BehaviorContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int insertSelective(BehaviorContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    List<BehaviorContext> selectByExample(BehaviorContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    BehaviorContext selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") BehaviorContext record, @Param("example") BehaviorContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int updateByExample(@Param("record") BehaviorContext record, @Param("example") BehaviorContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int updateByPrimaryKeySelective(BehaviorContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_context
     *
     * @mbggenerated Tue Dec 11 20:04:30 CST 2018
     */
    int updateByPrimaryKey(BehaviorContext record);
}