package com.my.dao;

import com.my.pojo.Classify;
import com.my.pojo.ClassifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int countByExample(ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int deleteByExample(ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int insert(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int insertSelective(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    List<Classify> selectByExample(ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    Classify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") Classify record, @Param("example") ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int updateByExample(@Param("record") Classify record, @Param("example") ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int updateByPrimaryKeySelective(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Sat Dec 08 23:57:06 CST 2018
     */
    int updateByPrimaryKey(Classify record);
}