package com.my.dao;

import com.my.pojo.DmContent;
import com.my.pojo.DmContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DmContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int countByExample(DmContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int deleteByExample(DmContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int insert(DmContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int insertSelective(DmContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    List<DmContent> selectByExample(DmContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    DmContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DmContent record, @Param("example") DmContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int updateByExample(@Param("record") DmContent record, @Param("example") DmContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int updateByPrimaryKeySelective(DmContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_content
     *
     * @mbggenerated Sat Dec 29 16:01:56 CST 2018
     */
    int updateByPrimaryKey(DmContent record);
}