package com.my.dao;

import com.my.pojo.FollowUser;
import com.my.pojo.FollowUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int countByExample(FollowUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int deleteByExample(FollowUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int deleteByPrimaryKey(Integer idfollowUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int insert(FollowUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int insertSelective(FollowUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    List<FollowUser> selectByExample(FollowUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    FollowUser selectByPrimaryKey(Integer idfollowUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") FollowUser record, @Param("example") FollowUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int updateByExample(@Param("record") FollowUser record, @Param("example") FollowUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int updateByPrimaryKeySelective(FollowUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_user
     *
     * @mbggenerated Thu Jan 03 21:38:29 CST 2019
     */
    int updateByPrimaryKey(FollowUser record);
}