package com.my.dao;

import com.my.pojo.PicVideo;
import com.my.pojo.PicVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PicVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int countByExample(PicVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int deleteByExample(PicVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int insert(PicVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int insertSelective(PicVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    List<PicVideo> selectByExample(PicVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    PicVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") PicVideo record, @Param("example") PicVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int updateByExample(@Param("record") PicVideo record, @Param("example") PicVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int updateByPrimaryKeySelective(PicVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_video
     *
     * @mbggenerated Wed Nov 14 14:07:11 CST 2018
     */
    int updateByPrimaryKey(PicVideo record);
}