package com.my.dao;

import com.my.pojo.UserBehavior;
import com.my.pojo.UserBehaviorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBehaviorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int countByExample(UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int deleteByExample(UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int insert(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int insertSelective(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    List<UserBehavior> selectByExample(UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    UserBehavior selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserBehavior record, @Param("example") UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByExample(@Param("record") UserBehavior record, @Param("example") UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_behavior
     *
     * @mbggenerated Mon Dec 10 21:16:58 CST 2018
     */
    int updateByPrimaryKey(UserBehavior record);
}