package com.my.dao;

import com.my.pojo.UserActive;
import com.my.pojo.UserActiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserActiveMapper {
    UserActive selectByUid(Integer userid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int countByExample(UserActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int deleteByExample(UserActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int insert(UserActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int insertSelective(UserActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    List<UserActive> selectByExample(UserActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    UserActive selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserActive record, @Param("example") UserActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int updateByExample(@Param("record") UserActive record, @Param("example") UserActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int updateByPrimaryKeySelective(UserActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_active
     *
     * @mbggenerated Tue Nov 13 00:05:22 CST 2018
     */
    int updateByPrimaryKey(UserActive record);
}