package com.my.dao;

import com.my.pojo.VideoWatch;
import com.my.pojo.VideoWatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoWatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int countByExample(VideoWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int deleteByExample(VideoWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int insert(VideoWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int insertSelective(VideoWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    List<VideoWatch> selectByExample(VideoWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    VideoWatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") VideoWatch record, @Param("example") VideoWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int updateByExample(@Param("record") VideoWatch record, @Param("example") VideoWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int updateByPrimaryKeySelective(VideoWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_watch
     *
     * @mbggenerated Tue Dec 25 10:10:40 CST 2018
     */
    int updateByPrimaryKey(VideoWatch record);
}