package com.my.dao;

import com.my.pojo.VideoClassify;
import com.my.pojo.VideoClassifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int countByExample(VideoClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int deleteByExample(VideoClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int insert(VideoClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int insertSelective(VideoClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    List<VideoClassify> selectByExample(VideoClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    VideoClassify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") VideoClassify record, @Param("example") VideoClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int updateByExample(@Param("record") VideoClassify record, @Param("example") VideoClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int updateByPrimaryKeySelective(VideoClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_classify
     *
     * @mbggenerated Sun Dec 09 03:44:15 CST 2018
     */
    int updateByPrimaryKey(VideoClassify record);
}