package com.my.dao;

import com.my.pojo.VideoLike;
import com.my.pojo.VideoLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int countByExample(VideoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int deleteByExample(VideoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int insert(VideoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int insertSelective(VideoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    List<VideoLike> selectByExample(VideoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    VideoLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") VideoLike record, @Param("example") VideoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int updateByExample(@Param("record") VideoLike record, @Param("example") VideoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int updateByPrimaryKeySelective(VideoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_like
     *
     * @mbggenerated Thu Dec 06 14:06:34 CST 2018
     */
    int updateByPrimaryKey(VideoLike record);
}