package com.spring.dao;

import com.my.pojo.CommentVideo;
import com.my.pojo.CommentVideoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CommentVideoMapper {
    List<CommentVideo> queryByPage(Map<String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int countByExample(CommentVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int deleteByExample(CommentVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int insert(CommentVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int insertSelective(CommentVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    List<CommentVideo> selectByExample(CommentVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    CommentVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") CommentVideo record, @Param("example") CommentVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int updateByExample(@Param("record") CommentVideo record, @Param("example") CommentVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int updateByPrimaryKeySelective(CommentVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_video
     *
     * @mbggenerated Mon Nov 12 21:58:04 CST 2018
     */
    int updateByPrimaryKey(CommentVideo record);
}