package com.spring.dao;

import com.my.pojo.UserVideo;
import com.my.pojo.UserVideoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int countByExample(UserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int deleteByExample(UserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int insert(UserVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int insertSelective(UserVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    List<UserVideo> selectByExample(UserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    UserVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserVideo record, @Param("example") UserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int updateByExample(@Param("record") UserVideo record, @Param("example") UserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int updateByPrimaryKeySelective(UserVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbggenerated Sun Nov 11 00:46:41 CST 2018
     */
    int updateByPrimaryKey(UserVideo record);
}